version: "3"

services:
  postgrest:
    container_name: postgREST
    image: postgrest/postgrest:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # Available environment variables documented here:
    # https://postgrest.org/en/latest/configuration.html#environment-variables
    environment:
      # The standard connection URI format, documented at
      # https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
      - PGRST_DB_URI=postgres://authenticator:mysecretpassword@db:5432/postgres
      # The name of which database schema to expose to REST clients
      - PGRST_DB_SCHEMA=api
      # The database role to use when no client authentication is provided
      - PGRST_DB_ANON_ROLE=web_anon
      # Overrides the base URL used within the OpenAPI self-documentation hosted at the API root path
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
      # JWT PASSWORD for todo_user (notice no quotes around below password)
      - PGRST_JWT_SECRET=O9fGlY0rDdDyW1SdCTaoqLmgQ2zZeCz6
    restart: unless-stopped
  admin:
    container_name: db-admin
    image: snowclone/admin:1.0.1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5173:5173"
    volumes:
      - ./admin:/admin
  server:
    image: snowclone/server:1.0.1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5175:5175"
    environment:
      PORT: "5175"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./server:/server
  eventserver:
    image: snowclone/eventserver:1.0.2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: db
      PG_PORT: "5432"
      PG_DATABASE: postgres
    volumes:
      - ./eventserver:/eventserver
  db:
    container_name: postgres
    image: snowclone/postgres:2.0.1
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/api/openapi.json
    volumes:
      - ./swagger:/api
    restart: unless-stopped
volumes:
  db:
    driver: local